/**:
  ros__parameters:
    imu:
      orientation: [0.0, 0.0, 0.0]

      # Sampling frequency for IMU data
      freq: 50 # Hz

      acc:
        std: 0.20

      gyro:
        std: 0.05

      ahrs:
        std: 0.01
