/**:
  ros__parameters:
    ukfm:
      # State vector is 9 so Uncertainty of the state vector must reflect that and be a square matrix 9x9
      # States: [Rotation (roll, pitch, yaw), Velocity (x, y, z), Position (x, y, z)]
      P_0: [1.000, 1.000, 1.000, 1.000, 1.000, 1.000, 10.000, 10.000, 10.000]

      # Alpha parameters for JUKF sigma point scaling.
      # JUKF uses 5 different sigma-point constructions internally:
      #   1) Reduced state propagation
      #   2) Process noise
      #   3) Reduced state update
      #   4) State augmentation
      #   5) Augmentation noise
      #
      # They control sigma spread (typically small, e.g. 1e-3)
      # In most cases you keep all equal
      alpha: [1e-3, 1e-3, 1e-3, 1e-3, 1e-3]
